app/config/routes.rb
Rails.application.routes.draw do

  resources :boolios
  root to: 'boolios#index'

end

app/app/models/boolio.rb
class Boolio < ActiveRecord::Base

  # callbacks to interact with booleans API
  before_create :create_baas
  before_save :update_baas
  before_destroy :destroy_baas

  @@base_url = 'https://api.booleans.io'

  def verify_with_api

    response = HTTParty.get( @@base_url + '/' + self.api_id )

    unless response.code == 200
      return false
    end

    attributes = JSON.parse response.body

    unless attributes['val'] != self.val
      # make sure we are in sync w/ the API service
      self.update(
        val: attributes['val']
      )
    end
  end

  private
    # create boolean via REST interface
    def create_baas

      # create boolean
      response = HTTParty.post( @@base_url,
        body: { val: self.val }
      )

      # Return false if unsuccessful
      unless response.code == 200
        return false
      end

      self.assign_attributes(
        api_id: response['id']
      )

      true
    end

    def update_baas

      # only want to check on existing items
      return true if self.new_record?

      # update boolean
      response = HTTParty.put( @@base_url + '/' + self.api_id,
        body: { val: self.val }
      )

      # Return false if unsuccessful
      response.code == 200

    end

    def destroy_baas

      # Destroy boolean
      response = HTTParty.delete( @@base_url + '/' + self.api_id )

      # Return false if unsuccessful
      response.code == 200

    end

end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/app/controllers/boolios_controller.rb
class BooliosController < ApplicationController
  before_action :set_boolio, only: [:show, :edit, :update, :destroy]

  # GET /boolios
  # GET /boolios.json
  def index
    @boolios = Boolio.all
  end

  # GET /boolios/1
  # GET /boolios/1.json
  def show

    # Get random gif from Giphy (http://giphy.com)
    response = HTTParty.get('http://api.giphy.com/v1/gifs/search?' +
      'q=' + @boolio.val.to_s +
      '&api_key=dc6zaTOxFJmzC' + # provided for public beta testing via (https://github.com/Giphy/GiphyAPI#public-beta-key)
      '&limit=1' + # only want 1
      '&offset=' + rand(30).to_s + # pull from the top 10 most relevant images
      '&rating=pg' + # afraid if this is any higher
      '&fmt=json' # seems to return JSON anyway, but just in case
    )

    if response.code == 200

      # conver to JSON
      json = JSON.parse response.body, object_class: OpenStruct

      # set image from returned results
      @image = json.data[0].images if json.data.count > 0
    end
    
  end

  # GET /boolios/new
  def new
    @boolio = Boolio.new
  end

  # GET /boolios/1/edit
  def edit
    @boolio.verify_with_api
  end

  # POST /boolios
  # POST /boolios.json
  def create

    # create local record (to keep for later purposes)
    @boolio = Boolio.new( 
      val: boolio_params[:val] == '1'
    )

    respond_to do |format|
      if @boolio.save
        format.html { redirect_to @boolio, notice: 'Boolio was successfully created.' }
        format.json { render :show, status: :created, location: @boolio }
      else
        format.html { render :new }
        format.json { render json: @boolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boolios/1
  # PATCH/PUT /boolios/1.json
  def update
    respond_to do |format|
      if @boolio.update( boolio_params )
        format.html { redirect_to @boolio, notice: 'Boolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @boolio }
      else
        format.html { render :edit }
        format.json { render json: @boolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boolios/1
  # DELETE /boolios/1.json
  def destroy
    @boolio.destroy
    respond_to do |format|
      format.html { redirect_to boolios_url, notice: 'Boolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boolio
      @boolio = Boolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boolio_params
      params.require(:boolio).permit(:val, :id)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/boolios_helper.rb
module BooliosHelper
end

app/app/helpers/root_helper.rb
module RootHelper
end

app/app/views/boolios/_form.html.erb
<br />
<%= form_for @boolio do |f| %>
  <div class="row">
    <fieldset class="small-6 columns">
      <div class="switch stretch">
        <%= f.check_box :val, class: 'switch-input' %>
        <%= f.label :val, class: 'switch-paddle' do %>
          <span class="switch-active" aria-hidden="true">True</span>
          <span class="switch-inactive" aria-hidden="true">False</span>
        <% end %>
      </div>
    </fieldset>
  </div>
  <br/ >
  <%= f.submit 'Save', class: 'button success' %>
<% end %>

app/app/views/boolios/edit.html.erb
<h3>Editing Boolio <span class="subheader"><%= @boolio.api_id %></span></h3>

<%= render 'form' %>

<div class="button-group">
  <%= link_to @boolio, class: 'button' do %> <i class="fi-magnifying-glass"></i> Show <% end %>
  <%= link_to boolios_path, class: 'button hollow' do %> <i class="fi-arrow-left"></i> Back <% end %>
</div>

app/app/views/boolios/index.html.erb
<% if notice %><div class="callout primary"><%= notice %></div> <% end %>
<h3>Listing Booleans</h3>
<div class="callout secondary">Baas: Booleans as a Service (<a href="https://booleans.io" target="_booleans">https://booleans.io</a>)</div>

<table class="stack hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>API ID</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @boolios.each do |boolio| %>
      <tr>
        <td><%= boolio.id %></td>
        <td><%= boolio.api_id %></td>
        <td>
          <% if boolio.val %>
            <span class="success label">TRUE</span>
          <% else %>
            <span class="alert label">FALSE</span>
          <% end %>
        </td>
        <td>
          <%= link_to boolio do %>
            <i class="fi-magnifying-glass"></i>
          <% end %>
          <%= link_to edit_boolio_path(boolio) do %>
            <i class="fi-pencil"></i>
          <% end %>
          <%= link_to boolio, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fi-x"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_boolio_path, class: 'button' do %> <i class="fi-plus"></i> Create New <% end %>

app/app/views/boolios/new.html.erb
<h3>New Boolean</h3>

<%= render 'form' %>

<%= link_to boolios_path, class: 'button hollow' do %>
  <i class="fi-arrow-left"></i> Back
<% end %>

app/app/views/boolios/show.html.erb
<% if notice %><div class="callout primary"><%= notice %></div><% end %>

<h3>Boolean <span class="subheader"><%= @boolio.api_id %></span></h3>

<p>
  Value: 
  <% if @boolio.val %>
    <span class="success label">TRUE</span>
  <% else %>
    <span class="alert label">FALSE</span>
  <% end %>
</p>

<% if( @image ) %>
<p>
  <img src="<%= @image.fixed_height.url %>" />
</p>
<% end %>

<br/>

<div class="button-group">
  <%= link_to boolios_path, class: 'button hollow' do %><i class="fi-arrow-left"></i> Back <% end %>
  <%= link_to edit_boolio_path(@boolio), class: 'button' do %><i class="fi-pencil"></i> Edit <% end %>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!--
    ========================================================
    This pattern is downloaded from www.subtlepatterns.com 
    If you need more, that's where to get'em.
    ========================================================
    -->

    <div id="application" class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <div id="server" class="callout"><%= ENV['HOST_OS'] || 'Unknown' %>: <%= ENV['HOST_IP'] || 'Address' %></div>
      </div>
    </div>

  </body>
</html>